// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zmqprotobuf.proto

#ifndef PROTOBUF_zmqprotobuf_2eproto__INCLUDED
#define PROTOBUF_zmqprotobuf_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace zmqprotobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_zmqprotobuf_2eproto();
void protobuf_AssignDesc_zmqprotobuf_2eproto();
void protobuf_ShutdownFile_zmqprotobuf_2eproto();

class PSMSG;

// ===================================================================

class PSMSG : public ::google::protobuf::Message {
 public:
  PSMSG();
  virtual ~PSMSG();

  PSMSG(const PSMSG& from);

  inline PSMSG& operator=(const PSMSG& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PSMSG& default_instance();

  void Swap(PSMSG* other);

  // implements Message ----------------------------------------------

  PSMSG* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PSMSG& from);
  void MergeFrom(const PSMSG& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // repeated float weights = 2;
  inline int weights_size() const;
  inline void clear_weights();
  static const int kWeightsFieldNumber = 2;
  inline float weights(int index) const;
  inline void set_weights(int index, float value);
  inline void add_weights(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      weights() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_weights();

  // repeated float gradients = 3;
  inline int gradients_size() const;
  inline void clear_gradients();
  static const int kGradientsFieldNumber = 3;
  inline float gradients(int index) const;
  inline void set_gradients(int index, float value);
  inline void add_gradients(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      gradients() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_gradients();

  // @@protoc_insertion_point(class_scope:zmqprotobuf.PSMSG)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< float > weights_;
  ::google::protobuf::RepeatedField< float > gradients_;
  ::google::protobuf::int32 type_;
  friend void  protobuf_AddDesc_zmqprotobuf_2eproto();
  friend void protobuf_AssignDesc_zmqprotobuf_2eproto();
  friend void protobuf_ShutdownFile_zmqprotobuf_2eproto();

  void InitAsDefaultInstance();
  static PSMSG* default_instance_;
};
// ===================================================================


// ===================================================================

// PSMSG

// required int32 type = 1;
inline bool PSMSG::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PSMSG::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PSMSG::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PSMSG::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 PSMSG::type() const {
  // @@protoc_insertion_point(field_get:zmqprotobuf.PSMSG.type)
  return type_;
}
inline void PSMSG::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:zmqprotobuf.PSMSG.type)
}

// repeated float weights = 2;
inline int PSMSG::weights_size() const {
  return weights_.size();
}
inline void PSMSG::clear_weights() {
  weights_.Clear();
}
inline float PSMSG::weights(int index) const {
  // @@protoc_insertion_point(field_get:zmqprotobuf.PSMSG.weights)
  return weights_.Get(index);
}
inline void PSMSG::set_weights(int index, float value) {
  weights_.Set(index, value);
  // @@protoc_insertion_point(field_set:zmqprotobuf.PSMSG.weights)
}
inline void PSMSG::add_weights(float value) {
  weights_.Add(value);
  // @@protoc_insertion_point(field_add:zmqprotobuf.PSMSG.weights)
}
inline const ::google::protobuf::RepeatedField< float >&
PSMSG::weights() const {
  // @@protoc_insertion_point(field_list:zmqprotobuf.PSMSG.weights)
  return weights_;
}
inline ::google::protobuf::RepeatedField< float >*
PSMSG::mutable_weights() {
  // @@protoc_insertion_point(field_mutable_list:zmqprotobuf.PSMSG.weights)
  return &weights_;
}

// repeated float gradients = 3;
inline int PSMSG::gradients_size() const {
  return gradients_.size();
}
inline void PSMSG::clear_gradients() {
  gradients_.Clear();
}
inline float PSMSG::gradients(int index) const {
  // @@protoc_insertion_point(field_get:zmqprotobuf.PSMSG.gradients)
  return gradients_.Get(index);
}
inline void PSMSG::set_gradients(int index, float value) {
  gradients_.Set(index, value);
  // @@protoc_insertion_point(field_set:zmqprotobuf.PSMSG.gradients)
}
inline void PSMSG::add_gradients(float value) {
  gradients_.Add(value);
  // @@protoc_insertion_point(field_add:zmqprotobuf.PSMSG.gradients)
}
inline const ::google::protobuf::RepeatedField< float >&
PSMSG::gradients() const {
  // @@protoc_insertion_point(field_list:zmqprotobuf.PSMSG.gradients)
  return gradients_;
}
inline ::google::protobuf::RepeatedField< float >*
PSMSG::mutable_gradients() {
  // @@protoc_insertion_point(field_mutable_list:zmqprotobuf.PSMSG.gradients)
  return &gradients_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace zmqprotobuf

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_zmqprotobuf_2eproto__INCLUDED
